defaults:
  google_client_id: '429049241111-jo0r6m00dtk6phpgl2paqh5m4n3hcknv.apps.googleusercontent.com'
  google_client_secret: 'fcq-u_3YsBWuCSwPc9ZMCapn'
  default_calendar: { summary: 'Atelier' }
  app_host: 'http://localhost:3000'
